# Generated by Django 5.1.6 on 2025-02-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
