# Generated by Django 5.1.6 on 2025-02-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_product_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolveRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('number_of_products', models.IntegerField()),
                ('number_of_truck_types', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('average_fill_rate', models.FloatField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('solution_data', models.JSONField()),
            ],
        ),
    ]
