# Generated by Django 5.1.6 on 2025-02-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0003_solverecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='solverecord',
            name='truck_names',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
