# Generated by Django 5.1.6 on 2025-02-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0004_solverecord_truck_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='solverecord',
            name='number_of_trucks_per_type',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
